name: .editorconfig
on:
  push:
    branches:
      - main
    paths:
      - ".editorconfig"
      - ".github/workflows/.editorconfig.yml"

# Eventually: https://github.com/actions/checkout?tab=readme-ov-file#checkout-multiple-repos-side-by-side
jobs:
  distribute:
    name: Distribute
    runs-on: ubuntu-24.04
    steps:
      - name: Get commit message
        id: commit-message
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "content=$(gh api repos/anttiharju/.editorconfig/commits/${{ github.sha }} --jq .commit.message)" >> "$GITHUB_OUTPUT"
      - name: Generate commit token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.ANTTIHARJU_BOT_ID }}
          private-key: ${{ secrets.ANTTIHARJU_BOT_PRIVATE_KEY }}
          repositories: vmatch
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: anttiharju/vmatch
          token: ${{ steps.generate-token.outputs.token }}
          path: anttiharju/vmatch
      - name: Print current branch name
        id: branch
        run: |
          git branch --show-current
#      - name: Update .editorconfig
#        working-directory: anttiharju/vmatch
#        run: |
#          git fetch origin update-editorconfig --no-tags || true
#          git switch update-editorconfig || git switch -c update-editorconfig
#          curl -o .editorconfig https://raw.githubusercontent.com/anttiharju/.editorconfig/${{ github.sha }}/.editorconfig
#      - name: Commit changes
#        id: commit-changes
#        uses: anttiharju/actions/commit-changes@v0
#        with:
#          working-directory: anttiharju/vmatch
#          committer: "anttiharju[bot]"
#          message: |
#            ${{ steps.commit-message.outputs.content }}
#
#            This is an automated commit, origin:
#            https://github.com/anttiharju/.editorconfig/blob/${{ github.sha }}/.github/workflows/.editorconfig.yml
#      - if: steps.commit-changes.outputs.changed == 'true'
#        name: Create Pull Request
#        working-directory: anttiharju/vmatch
#        env:
#          GH_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
#        run: |
#          pr_url=$(gh pr create \
#            --title "Update .editorconfig" \
#            --body "This is an automated PR" \
#            --base main \
#            --head update-editorconfig)
#
#          gh pr merge "$pr_url" --squash --auto
