name: Distribute
on:
  push:
    branches:
      - main
    paths:
      - ".editorconfig"
      - ".github/workflows/distribute.yml"

jobs:
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-24.04
    steps:
      - name: Generate commit token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.ANTTIHARJU_BOT_ID }}
          private-key: ${{ secrets.ANTTIHARJU_BOT_PRIVATE_KEY }}
          repositories: vmatch
      - name: Update vmatch
        uses: ./.github/actions/update-repo
        with:
          repository: vmatch
          token: ${{ steps.generate-token.outputs.token }}
