name: Distribute
on:
  push:
    branches:
      - main
    paths:
      - ".editorconfig"
      - ".github/workflows/distribute.yml"

# Eventually: https://github.com/actions/checkout?tab=readme-ov-file#checkout-multiple-repos-side-by-side
jobs:
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-24.04
    steps:
      - name: Generate commit token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.ANTTIHARJU_BOT_ID }}
          private-key: ${{ secrets.ANTTIHARJU_BOT_PRIVATE_KEY }}
          repositories: vmatch
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: anttiharju/vmatch
          token: ${{ steps.generate-token.outputs.token }}
          path: anttiharju/vmatch
      - name: Get default branch name
        working-directory: anttiharju/vmatch
        id: branch
        run: |
          echo "default=$(git branch --show-current)" >> "$GITHUB_OUTPUT"
      - name: Update .editorconfig
        working-directory: anttiharju/vmatch
        run: |
          git fetch origin update-editorconfig --no-tags || true
          git switch update-editorconfig || git switch -c update-editorconfig
          curl -o .editorconfig https://raw.githubusercontent.com/anttiharju/.editorconfig/${{ github.sha }}/.editorconfig
      - name: Commit changes
        id: commit-changes
        uses: anttiharju/actions/commit-changes@v0
        with:
          working-directory: anttiharju/vmatch
          committer: "anttiharju[bot]"
          message: |
            ${{ github.event.head_commit.message }}

            Update .editorconfig to
            https://github.com/anttiharju/.editorconfig/blob/${{ github.sha }}/.editorconfig
      - if: steps.commit-changes.outputs.changed == 'true'
        name: Create Pull Request
        working-directory: anttiharju/vmatch
        env:
          GH_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
          default_branch: ${{ steps.branch.outputs.default }}
          body: |
            This is an automated PR from https://github.com/anttiharju/.editorconfig/blob/${{ github.sha }}/.github/workflows/distribute.yml
        run: |
          pr_open=$(gh pr list --head update-editorconfig --json state --jq '.[0].state')

          if [ "$pr_open" = "OPEN" ]; then
            echo "PR already exists"
          else
            pr_url=$(gh pr create \
              --title "${{ github.event.head_commit.message }}" \
              --body "$body" \
              --base "$default_branch" \
              --head update-editorconfig)

            gh pr merge "$pr_url" --squash --auto
          fi
