name: Distribute
on:
  push:
    branches:
      - main
    paths:
      - ".editorconfig"
      - ".github/workflows/distribute.yml"

jobs:
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Generate commit token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.ANTTIHARJU_BOT_ID }}
          private-key: ${{ secrets.ANTTIHARJU_BOT_PRIVATE_KEY }}
          repositories: vmatch,actions,relcheck,homelab,nix-darwin,rust-book,nur-packages,go-starter
      - name: vmatch
        uses: ./.github/actions/update-editorconfig
        with:
          repository: vmatch
          committer: "anttiharju[bot]"
          pr-token: ${{ secrets.PULL_REQUEST_TOKEN }}
          token: ${{ steps.generate-token.outputs.token }}
      - name: actions
        uses: ./.github/actions/update-editorconfig
        with:
          repository: actions
          committer: "anttiharju[bot]"
          pr-token: ${{ secrets.PULL_REQUEST_TOKEN }}
          token: ${{ steps.generate-token.outputs.token }}
      - name: relcheck
        uses: ./.github/actions/update-editorconfig
        with:
          repository: relcheck
          committer: "anttiharju[bot]"
          pr-token: ${{ secrets.PULL_REQUEST_TOKEN }}
          token: ${{ steps.generate-token.outputs.token }}
      - name: homelab
        uses: ./.github/actions/update-editorconfig
        with:
          repository: homelab
          committer: "anttiharju[bot]"
          pr-token: ${{ secrets.PULL_REQUEST_TOKEN }}
          token: ${{ steps.generate-token.outputs.token }}
      - name: nix-darwin
        uses: ./.github/actions/update-editorconfig
        with:
          repository: nix-darwin
          committer: "anttiharju[bot]"
          pr-token: ${{ secrets.PULL_REQUEST_TOKEN }}
          token: ${{ steps.generate-token.outputs.token }}
          automerge: false
      - name: rust-book
        uses: ./.github/actions/update-editorconfig
        with:
          repository: rust-book
          committer: "anttiharju[bot]"
          pr-token: ${{ secrets.PULL_REQUEST_TOKEN }}
          token: ${{ steps.generate-token.outputs.token }}
          automerge: false
      - name: nur-packages
        uses: ./.github/actions/update-editorconfig
        with:
          repository: nur-packages
          committer: "anttiharju[bot]"
          pr-token: ${{ secrets.PULL_REQUEST_TOKEN }}
          token: ${{ steps.generate-token.outputs.token }}
          automerge: false
      - name: go-starter
        uses: ./.github/actions/update-editorconfig
        with:
          repository: go-starter
          committer: "anttiharju[bot]"
          pr-token: ${{ secrets.PULL_REQUEST_TOKEN }}
          token: ${{ steps.generate-token.outputs.token }}
          automerge: false
