name: Distribute
on:
  push:
    branches:
      - main
    paths:
      - ".editorconfig"
      - ".github/workflows/distribute.yml"

jobs:
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .editorconfig
          sparse-checkout-cone-mode: false # todo: read about this, following actions/checkout recommendation atm
      - name: Generate commit token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.ANTTIHARJU_BOT_ID }}
          private-key: ${{ secrets.ANTTIHARJU_BOT_PRIVATE_KEY }}
          repositories: vmatch,actions
      - name: vmatch
        uses: anttiharju/actions/update-editorconfig@v0
        with:
          repository: vmatch
          token: ${{ steps.generate-token.outputs.token }}
          pr-token: ${{ secrets.PULL_REQUEST_TOKEN }}
      - name: actions
        uses: anttiharju/actions/update-editorconfig@v0
        with:
          repository: actions
          token: ${{ steps.generate-token.outputs.token }}
          pr-token: ${{ secrets.PULL_REQUEST_TOKEN }}
